### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by ONE-creator** [dianhsu/transformer-cpp-cpu#2]
请问大佬用C++完全实现了吗，能运行了吗

**Comment by dianhsu** [comment]
是的

**Comment by ONE-creator** [comment]
请问如何运行呢，我在VS中，运行前代码不报错，运行时失败

**Comment by dianhsu** [comment]
要用gcc环境

**Comment by dianhsu** [comment]
没在visual studio下面测试

**Comment by ONE-creator** [comment]
请问运行结果是这样吗
parameters count: 168544
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by dianhsu** [comment]
是这样的，因为我这个模型主要是用来看结构和跑数据量的，不看内部数据和结果

**Comment by ONE-creator** [comment]
好的好的，多谢解答
